Feature/multiplex (#11)
* feat: IO multiplex (kqueue, epoll)

* test: add multiplexing test

* fix: kevent don't use bit flags

* fix: netcat command not found error

* fix: undeclare macro in bsd

* style: int -> const int

* chore: remove #pragma once in header

* chore: build error in libconfig.a

```sh
/Applications/Xcode.app/Contents/Developer/usr/bin/make libconfig.a
c++ -Wall -Wextra -Werror -Wpedantic -std=c++98 -MMD -MP  -I.    -c -o .objs/config.o config.cpp
In file included from config.cpp:1:
./config.hpp:37:24: error: no newline at end of file [-Werror,-Wnewline-eof]
                       ^
1 error generated.
make[3]: *** [.objs/config.o] Error 1
make[2]: *** [all] Error 2
```

* chore: specify TOPDIR in the first line

* refactor: init with structure declaration

* Revert "refactor: init with structure declaration"

This reverts commit 136ad54e74ed40eddd3416116494e0b9e448f248.

since c++20....

* fix: perror is prohibited.

* feat: if close socket, delete IOEvent in Multiplex