Release -> main (#69)
* Feat: add config build rules

* Feat: add config test

* Feat: Add config class

* Fix: Header include path edit

* Feat: Add gitignore

* Feat: edit server name

* Feat: test code edit

* Feat: multiple server support

* test: refactoring

* fix: c++11 -> c++89에 맞게 수정

* chore: -Wpedantic option add

* Update README.md

* Delete README.md

* Revert "Delete README.md"

This reverts commit de2e8dff11aecb71295daa0e95a9163f0da7c096.

* Revert "Update README.md"

This reverts commit 280f1c759754d5ff68c91e3c1e0e3609bb35c76c.

* Feat: default constructor with default config file

* Feature/multiplex (#11)

* feat: IO multiplex (kqueue, epoll)

* test: add multiplexing test

* fix: kevent don't use bit flags

* fix: netcat command not found error

* fix: undeclare macro in bsd

* style: int -> const int

* chore: remove #pragma once in header

* chore: build error in libconfig.a

```sh
/Applications/Xcode.app/Contents/Developer/usr/bin/make libconfig.a
c++ -Wall -Wextra -Werror -Wpedantic -std=c++98 -MMD -MP  -I.    -c -o .objs/config.o config.cpp
In file included from config.cpp:1:
./config.hpp:37:24: error: no newline at end of file [-Werror,-Wnewline-eof]
                       ^
1 error generated.
make[3]: *** [.objs/config.o] Error 1
make[2]: *** [all] Error 2
```

* chore: specify TOPDIR in the first line

* refactor: init with structure declaration

* Revert "refactor: init with structure declaration"

This reverts commit 136ad54e74ed40eddd3416116494e0b9e448f248.

since c++20....

* fix: perror is prohibited.

* feat: if close socket, delete IOEvent in Multiplex

* Feature/http (#15)

* fix: distinct and refesh error in c++98

* remove: unused sample library

* feat: add update event in multiplex

* feat: http module

* test: curl test in makefile

* refactor: redesign http

* Develop: config parsing (#16)

* test: config test code edit

* chore: config file edit

* Feat: config logic change

* Chore: default config file edit

* Test: test code edit

* Feat: Config parsing

* Fix: c++11 error

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>
Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

* Config Parser - Return add and code style edit (#17)

* Test: return test

* Chore: return support

* Feat: return support

* Chore: <algorithm> header add

* Fix: parse_return - code range check

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* chore: add gitignore

* chore: rename configs -> data for pitchfork layout

* test: add update() to fix build error

* feat: httpMethod: delete, index: index

* Chore: folder move

* Feat: underscore remove && struct constructor

* Chore: event remove

* Test: test code update

* Feat: comment support

* Feat: allow, deny -> allows, denys; multiple allow, deny in one block

* Feat: struct linger

* Feat: ParseLimitExcept logic update

* Chore: getter pending

* Chore: default value init change int(-1), string("")

* Chore: build fix

* Feat: config parsing

* chore: config test

* Feat: loda config file

* Test: config logic fix

* Chore: restore minjung's conf

* Develop: URI 파싱 (#24)

* Feat: GetPath, GetLocation

* Test: GetPath test

* Test: GetPath, GetLocation

* Fix: GetPath, GetLocation

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* Listen reuseport type change from bool to int (#26)

* Fix: config error process

* Fit: listen bool type member -> int type

* Feat: listen reuseport

* Fix: std::runtime_error -> print error

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* fix: response body copy error #27

* fix: http header case insensitive #21

* chore: mv http directory for dependency

* chore: me http method directory for dependency

* 중복 listen 포트 체크, client GetUrl, GetPath, GetLocation 구현 (#29)

* Feat: GetPath, GetLocation moved to client

* Feat: GetUrl, GetPath, GetLocation

* Test: remove GetUrl, GetPath, GetLocation test

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* Server, Client 생성자 수정 (#30)

* Feat: GetPath, GetLocation moved to client

* Feat: GetUrl, GetPath, GetLocation

* Test: remove GetUrl, GetPath, GetLocation test

* Feat: Delete some functions

* Feat: Server, Client Construction edit

* Feat: logic change

* Feat: Conf constructor

* Feat: Conf change

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* chore: fix build error (#31)

* Fix: slash로 끝나지 않는 location 찾지 못하는 문제, 폴더를 열었을 때 에러처리를 하지 못하는문제 (#32)

* Fix: slash ended locatiog not found bug

* Fix: change bug fix logic

* Fix: location name + "/" if location name not ended with "/"

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* return 및 error_page 키워드에 대한 기능 추가  (#33)

* fix: find location error #32

* feat: do return, error_page keyword

* fix: return text

* fix: set kNotFound

* Fix: listen address default value change from "*" to "0.0.0.0" (#34)

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* listen address default value change from "*" to "0.0.0.0" && Cppcheck (#35)

* Fix: listen address default value change from "*" to "0.0.0.0"

* Style: cppcheck

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* refactor: remove duplicate setsocket function

* Feat: conf 정보 http의 member로 추가 (#37)

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* feat: method interface (#38)

* index, autoindex 기능추가 (#39)

feat: add index, autoindex 

---------

Co-authored-by: Seongmin Jo <seojo@c5r4s1.42seoul.kr>

* delete 기능추가 (#44)

feat: delete method

---------

Co-authored-by: Seongmin Jo <seojo@c5r4s1.42seoul.kr>

* chunk message 요청 받기  (#45)

* fix: refactor and fix minor error

* fix: access erorr

* feat: chunked message #42

* refactor: execute method after received

* 쿠키와 세션 (#49)

* feat: cookie & sesstion

* fix: session.cpp->makeSessionId()

* feat: add cgi socket

* feat: limit body size

* #51 + location ubuntu_cgi_tester, root의 slash 제거 (#53)

* Fix: path error (#51)

* Fix: path error

* Fix: add slash at root

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* Fix: remove slash at cgi_tester

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* fix: double execute error

* feat: add query header from uri

* Feat: add fastcgi_pass, PATH_INFO (#54)

* Feat: add fastcgi_pass, PATH_INFO

* Feat: execute cgi based on extension

* Feat: limit except use

* Fix: include order error

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>
Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

* Post: file upload and cgi process (#55)

* Feat: post method with file upload and cgi

* Feat: status code setting

* fix: autoindex title (path -> url)

* fix: Fix to not try to parse if post body is 0

* Cgi 수정 (#58)

* refactor: call cgi

* feat: put

* refactor: set response status directly

* feat: process cgi

* Test: add tester

* Test: add ubuntu tester

* Test: test envirionment setting

* TEST: test envirion setting

* fix: POST with a size of 100000000

* Test: test 환경 구성 (#59)

* Test: add tester

* Test: add ubuntu tester

* Test: test envirionment setting

* TEST: test envirion setting

* Test: conf edit

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* perf: client buf size up because of 10000000 test

* Cgi_pass를 항상 절대경로로 받아야 함 && Cgi waitpid는 pid 값이 -1일 때만 하기 (#60)

* Feat: cgi_pass should be absolute

* Fix: waitpid works if pid_ == -1

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* test: chmod +x tester

* fix: client_max_body_size error

* fix: check cgi access

* fix: cgi 100000000 error

* test: fix test_template.conf for tester

* Feat: www directory add (#62)

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* test: fix cgi_tester path not found error

* fix: include csignal

* fix: dead process and return 141 (SIGPIPE)

* fix: response header trim

* fix: cgi_tester 100000000 no return error

* fix: cgi_tester 100000000 EOF error

* fix: http_request member don't clear issue

* fix: cgi with special header error

Test POST http://localhost:8080/directory/youpi.bla with a size of 100000 with special header

- CGI에서 대문자로 변환해야하므로 기본키도 대문자로 변경함

* fix: cgi_tester post_body return code error

Test POST http://localhost:8080/post_body with a size of 0
Test POST http://localhost:8080/post_body with a size of 100
Test POST http://localhost:8080/post_body with a size of 200
Test POST http://localhost:8080/post_body with a size of 101

* refactor: buffer size up

* fix: pure virtual function call error

* refactor: more multiplex handling

* chore: add close log

* fix: status clear error

no more headers

* fix : redirect return code

* Feat: cgi php calculator and python file uploader (#63)

* Feat: cgi php calculator and python file uploader

* Fix: path와 file을 혼동하여 사용해서 발생하는 문제 해결

* Feat: envp에 content 전달

* Feat: post body from stdin, not from envp content

* chore: delete test file

* fix: 디렉토리 찾을 수 없는 오류 수정

* Fix: php cgi request method change (post -> get)

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>
Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

* fix: cgi_tester requriements

* feat: response set-cookie

* feat: add timeout in cgi

* new cgi (#64)

* Feat: test rule

* Feat: location myfiles

* Fix: body read issue

* Feat: body read issue resolve

* Feat: new cgi

* Feat: new cgi

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>

* Conf 구조 수정 (#65)

* Fix: conf structure edit

* Feat: error page

* remove: debug message

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>
Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

* fix: fix error_page

* fix: python interal server error (#66)

* fix: c++11 compile error

* remove: siege.conf

* remove: move html to resource

* test: merge conf files

* test: add favicon, merge location in conf

* fix: add base href because relative path error

* fix: error_page erorr

* test: if make conf, mkdir uploaded_files

* Update: main.cpp default config path

* fix: add fcntl

---------

Co-authored-by: juwkim <gimjuwon-ui-MacBookPro.local>
Co-authored-by: 김주원 <66457470+juwkim@users.noreply.github.com>
Co-authored-by: Seongmin Jo <seojo@cx2r5s6.42seoul.kr>
Co-authored-by: seojo <71538487+joseoungmin@users.noreply.github.com>
Co-authored-by: Seongmin Jo <seojo@c5r4s1.42seoul.kr>